name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    # Build project
    - name: mkdir
      run: mkdir build
    - name: cmake build
      run: cmake -Bbuild -H.
    - name: cmake make
      run: cmake --build build/ --target all
      env:
        MAKEFLAGS: "-j2"
        
    # run tests
    - name: RunTests
      run: home/runner/work/WordCount/WordCount/build/tests/tests
      
    # upload exe
    - name: Create EXE
      uses: actions/upload-artifact@v1
      with:
        name: Upload exe
        path: build/WordCount
        
    #- name: configure
    #  run: ./configure
    #- name: make
    #  run: make
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
